name: Build docker image

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
      - "**/README.*"
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}   
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t yuankai619/ordernow-backend .
      - name: Push to Dockerhub
        run: docker push yuankai619/ordernow-backend:latest