name: Deploy

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**/*.md"
      - "**/README.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      PORT: ${{ secrets.PORT }}
      ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.4

      - name: Run tests
        run: ./gradlew test

      - name: Build project
        run: ./gradlew build
