name: Deploy

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "**/*.md"
      - "**/README.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      TESTING_DB_NAME: ${{ secrets.TESTING_DB_NAME }}
      PORT: ${{ secrets.PORT }}
      ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}

    steps:
#      - name: Debug Environment Variables
#        run: |
#          echo "Checking environment variables..."
#          echo "DB_USER is set: ${{ ! env.DB_USER == '' }}"
#          echo "DB_PASSWORD is set: ${{ ! env.DB_PASSWORD == '' }}"
#          echo "DB_NAME is set: ${{ ! env.DB_NAME == '' }}"
#          echo "TESTING_DB_NAME is set: ${{ ! env.TESTING_DB_NAME == '' }}"
#          echo "PORT is set: ${{ ! env.PORT == '' }}"
#          echo "ALLOWED_ORIGIN is set: ${{ ! env.ALLOWED_ORIGIN == '' }}"
#
#          echo "PORT: ${{ env.PORT }}"
#          echo "ALLOWED_ORIGIN: ${{ env.ALLOWED_ORIGIN }}"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.6.4

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
