name: Deploy

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "**/*.md"
      - "**/README.*"
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "**/*.md"
      - "**/README.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      TESTING_DB_NAME: ${{ secrets.TESTING_DB_NAME }}
      PORT: ${{ secrets.PORT }}
      ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET }}
      MAIL_NAME: ${{secrets.MAIL_NAME }}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.4
          gradle-home-cache-cleanup: true

      - name: Build project
        run: ./gradlew build
